POST https://stunning-space-happiness-7vq96vr97vv53wp7r-8080.app.github.dev/cal
Content-Type: application/json

{
      "cards":{ "hand": ["C8", "D9"],
               "position":0,
              "publicCards": ["HK","S9","H7","H10"]
                    },
      "table":{"person":6,
        "action":["1","3","allin"]
      }               
}
