POST https://fluffy-fortnight-jj64qv579r7g2q4xr-8080.app.github.dev/cal
Content-Type: application/json

{
      "cards":{ "hand": ["D3", "SA"],
               "position":0,
              "publicCards": []
                    },
      "table":{"person":3,
        "action":[25,25]
      }               
}
